[package]
name = "github-pr-review"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/github-pr-review.rs"
crate-type = ["cdylib"]

[dependencies]
dotenv = "0.15.0"
github-flows = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"
anyhow = "1"
flowsnet-platform-sdk = "0.1"
lazy_static = "1.4.0"
regex = "1.7.1"
llmservice-flows = "0.2.0"
words-count = "0.1.4"
log = "0.4"
tokio_wasi = { version = "1.25.1", features = ["macros", "rt"] }
http_req_wasi = { version = "0.10.2", features = ["wasmedge_ssl"] }
